# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kcommit < Formula
  desc "Git commit generator using Karma style."
  homepage "https://github.com/BMilliet/kcommit"
  version "0.1.4"
  license "MIT License"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/BMilliet/kcommit/releases/download/0.1.4/kcommit_Darwin_x86_64.tar.gz"
      sha256 "fe252aee8a9dc8eba4e52dd602338ba436c97b1a96e1c14fce44b9b8761e8deb"

      def install
        bin.install "kc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/BMilliet/kcommit/releases/download/0.1.4/kcommit_Darwin_arm64.tar.gz"
      sha256 "312715b4f0f9f51cd7b795acc95dc0ee9b9f414ee696d24e7854d4aafddac9bd"

      def install
        bin.install "kc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/BMilliet/kcommit/releases/download/0.1.4/kcommit_Linux_x86_64.tar.gz"
        sha256 "cb2e2ffef979a070fa378e33b5771b9f8ad1d8a224ae0fe32fa881cdeac3ab41"

        def install
          bin.install "kc"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/BMilliet/kcommit/releases/download/0.1.4/kcommit_Linux_arm64.tar.gz"
        sha256 "76a86064300b4a2a4d656213223d0aa564374c4b9b5ff5ca2e6042fa8e1eff0a"

        def install
          bin.install "kc"
        end
      end
    end
  end
end
